/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 calculator_button.glb --transform --keepmeshes --keepmaterials 
Files: calculator_button.glb [9.04KB] > calculator_button-transformed.glb [3.38KB] (63%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function CalculatorButton(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./3D_Assets/calculator_button-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Button">
          <mesh name="Button_1" geometry={nodes.Button_1.geometry} material={materials.Button_Body} />
          <mesh name="Button_2" geometry={nodes.Button_2.geometry} material={materials.Pressed_Button_Indicator} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./3D_Assets/calculator_button-transformed.glb')
