/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 calculator_body.glb --transform --keepmeshes --keepmaterials 
Files: calculator_body.glb [56.37KB] > calculator_body-transformed.glb [6.51KB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CalculatorBody(props) {
  console.log('hehe')
  const { nodes, materials } = useGLTF('./3D_Assets/calculator_body-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <mesh geometry={nodes.Body.geometry} material={materials.Calculator_Body} />
      <mesh geometry={nodes.Screen.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Screen_Inner_Rim_And_Bottom_1.geometry} material={materials.Screen_Inner_Rim_And_Back} />
      <mesh geometry={nodes.Screen_Inner_Rim_And_Bottom_2.geometry} material={materials.Calculator_Body} />
    </group>
  )
}

useGLTF.preload('./3D_Assets/calculator_body-transformed.glb')
