/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 calculator_button.glb --transform --keepmeshes --keepmaterials 
Files: calculator_button.glb [9.04KB] > calculator_button-transformed.glb [3.38KB] (63%)
*/

import React, { createContext, useContext, useMemo, useRef } from 'react'
import { useGLTF, useAnimations, Merged, Html } from '@react-three/drei'
import { FrontSide, MeshStandardMaterial } from 'three';
import * as THREE from 'three'

const context = createContext();

export function Instances({children}) {
  const {nodes} = useGLTF('./3D_Assets/calculator_button-transformed.glb')

  const instances = useMemo(
    () => ({
      ButtonRim: nodes.Button_1,
      ButtonBody: nodes.Button_2
    }), 
    [nodes]
  )

  return (
		<group dispose={null}>
			<Merged meshes={instances} position={[0, 0, .43]}>
				{(instances) => <context.Provider value={instances} children={children} />}
			</Merged>
		</group>
  )
}

export function CalculatorButton({id, char, position, rotation, scale}) {
  const group = useRef()
  const instances = useContext(context)
  const { materials, animations } = useGLTF('./3D_Assets/calculator_button-transformed.glb')
  const { actions } = useAnimations(animations, group)

  const symbolMaterial = new MeshStandardMaterial({
    color: new THREE.Color( 0x003986 ),
    side: THREE.DoubleSide,
  })

  const symbolPosition = new THREE.Vector3(0, .697, 0)

  return (
    <group ref={group} dispose={null} position={position} rotation={rotation} scale={scale}>
      <Html
        transform
        position={symbolPosition}
        rotation={char === "←" ? [-Math.PI/2, 0, -Math.PI/2] : [-Math.PI/2, 0, 0]}
        scale={char === "←" ? [1, .75, 1] : [1, 1, 1]}
        material={symbolMaterial}
        occlude
        // color="#003986"
      >
        <p>{char}</p>
      </Html>
      <group name="Scene">
        <group name="Button">
          <instances.ButtonRim />
          <instances.ButtonBody />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./3D_Assets/calculator_button-transformed.glb')
